<?php

namespace Bigfoot\Bundle\ContextBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContextualizedEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContextualizedEntityRepository extends EntityRepository
{
}
